name: Build and publish Windows XP/7 binary

on:
  workflow_dispatch:

jobs:
  build_for_windows_xp:
    name: Build for windows XP
    runs-on: windows-2022
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Clone itarmykit main repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'opengs'
          repository: 'itarmykit'
      - name: Install dependencies
        run: |
          cd itarmykit
          npm install -g @quasar/cli yarn --force
          rm package.json, yarn.lock, quasar.config.js
          ren package.winxp.json package.json
          ren quasar.config.winxp.js quasar.conf.js
          yarn install
      - name: Build and release WindowsXP binaries 
        env:
          EP_GH_IGNORE_TIME: true
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win32 --icon=/src-electron/icons/icon.ico